package com.psi.easymanager.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END

/**
 * 折扣方案
 */
public class PxDiscounScheme implements java.io.Serializable {

    private Long id;
    /**
     * 对应服务器id
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 折扣方案名称
     */
     @Expose
    private String name;
    /**
     * 折扣值(0-100)
     */
     @Expose
    private Integer rate;
    /**
     * 方案类型(0:折扣 1：会员)
     */
     @Expose
    private String type;
    /**
     * 虚拟删除 0：正常 1：删除 2：审核
     */
     @Expose
    private String delFlag;

    // KEEP FIELDS - put your custom fields here
    private boolean isSelected;//标记选中，方案打折选择状态
    // KEEP FIELDS END

    public PxDiscounScheme() {
    }

    public PxDiscounScheme(Long id) {
        this.id = id;
    }

    public PxDiscounScheme(Long id, String objectId, String name, Integer rate, String type, String delFlag) {
        this.id = id;
        this.objectId = objectId;
        this.name = name;
        this.rate = rate;
        this.type = type;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    // KEEP METHODS - put your custom methods here
    public boolean isSelected() {
        return isSelected;
    }

    public void setIsSelected(boolean isSelected) {
        this.isSelected = isSelected;
    }
    // KEEP METHODS END

}
