package com.psi.easymanager.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END

/**
 * 附加费信息
 */
public class PxExtraCharge implements java.io.Serializable {

    private Long id;
    /**
     * 对应服务器id
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 附加费名称
     */
     @Expose
    private String name;
    /**
     * 服务费
     */
     @Expose
    private Double serviceCharge;
    /**
     * 计费标准(0:每桌固定 1：按人数 2：按时间)
     */
     @Expose
    private String serviceType;
    /**
     * 最低消费金额
     */
     @Expose
    private Double minConsume;
    /**
     * 是否启用服务费(0:不启用 1:启用)
     */
     @Expose
    private String serviceStatus;
    /**
     * 是否启动最低消费(0:不启用 1:启用)
     */
     @Expose
    private String consumeStatus;
    /**
     * 计费时长
     */
     @Expose
    private Integer minutes;
    /**
     * 虚拟删除 0：正常 1：删除 2：审核
     */
     @Expose
    private String delFlag;

    // KEEP FIELDS - put your custom fields here
  public static final String SERVICE_TYPE_FIXED = "0";
  public static final String SERVICE_TYPE_PEOPLE = "1";
  public static final String SERVICE_TYPE_TIME = "2";

  public static final String ENABLE_FALSE = "0";
  public static final String ENABLE_TRUE = "1";

  public static final String MINIMUM_CHARGE_TRUE = "1";
  public static final String MINIMUM_CHARGE_FALSE = "0";
    // KEEP FIELDS END

    public PxExtraCharge() {
    }

    public PxExtraCharge(Long id) {
        this.id = id;
    }

    public PxExtraCharge(Long id, String objectId, String name, Double serviceCharge, String serviceType, Double minConsume, String serviceStatus, String consumeStatus, Integer minutes, String delFlag) {
        this.id = id;
        this.objectId = objectId;
        this.name = name;
        this.serviceCharge = serviceCharge;
        this.serviceType = serviceType;
        this.minConsume = minConsume;
        this.serviceStatus = serviceStatus;
        this.consumeStatus = consumeStatus;
        this.minutes = minutes;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getServiceCharge() {
        return serviceCharge;
    }

    public void setServiceCharge(Double serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public Double getMinConsume() {
        return minConsume;
    }

    public void setMinConsume(Double minConsume) {
        this.minConsume = minConsume;
    }

    public String getServiceStatus() {
        return serviceStatus;
    }

    public void setServiceStatus(String serviceStatus) {
        this.serviceStatus = serviceStatus;
    }

    public String getConsumeStatus() {
        return consumeStatus;
    }

    public void setConsumeStatus(String consumeStatus) {
        this.consumeStatus = consumeStatus;
    }

    public Integer getMinutes() {
        return minutes;
    }

    public void setMinutes(Integer minutes) {
        this.minutes = minutes;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
