package com.psi.easymanager.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.Expose;
// KEEP INCLUDES END

/**
 * 操作记录
 */
public class PxOperationLog implements java.io.Serializable {

    private Long id;
    /**
     * 订单号
     */
     @Expose
    private String orderNo;
    /**
     * 操作人名称
     */
     @Expose
    private String operater;
    /**
     * 商品名称
     */
     @Expose
    private String productName;
    /**
     * 类型 0：退单 1：撤单
     */
     @Expose
    private String type;
    /**
     * 操作缘由
     */
     @Expose
    private String remarks;
    /**
     * 公司ID
     */
     @Expose
    private String cid;
    /**
     * 操作日期
     */
     @Expose
    private Long operaterDate;
    /**
     * 价格
     */
     @Expose
    private Double totalPrice;

    // KEEP FIELDS - put your custom fields here
  public static final String TYPE_REFUND = "0";
  public static final String TYPE_REVOKE = "1";
    // KEEP FIELDS END

    public PxOperationLog() {
    }

    public PxOperationLog(Long id) {
        this.id = id;
    }

    public PxOperationLog(Long id, String orderNo, String operater, String productName, String type, String remarks, String cid, Long operaterDate, Double totalPrice) {
        this.id = id;
        this.orderNo = orderNo;
        this.operater = operater;
        this.productName = productName;
        this.type = type;
        this.remarks = remarks;
        this.cid = cid;
        this.operaterDate = operaterDate;
        this.totalPrice = totalPrice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getOperater() {
        return operater;
    }

    public void setOperater(String operater) {
        this.operater = operater;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public Long getOperaterDate() {
        return operaterDate;
    }

    public void setOperaterDate(Long operaterDate) {
        this.operaterDate = operaterDate;
    }

    public Double getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
