package com.psi.easymanager.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.Expose;
// KEEP INCLUDES END

/**
 * 订单号码
 */
public class PxOrderNum implements java.io.Serializable {

    private Long id;
    /**
     * 开单日期
     */
     @Expose
    private String date;
    /**
     * 开单数量
     */
     @Expose
    private Integer num;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PxOrderNum() {
    }

    public PxOrderNum(Long id) {
        this.id = id;
    }

    public PxOrderNum(Long id, String date, Integer num) {
        this.id = id;
        this.date = date;
        this.num = num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
