package com.psi.easymanager.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END

/**
 * 翼支付实体参数
 */
public class PxWingPay implements java.io.Serializable {

    private Long id;
    /**
     * 对应服务器id
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 桌号
     */
     @Expose
    private String orderTable;
    /**
     * 订单号
     */
     @Expose
    private String orderNo;
    /**
     * 流水号
     */
     @Expose
    private String orderSerialNum;
    /**
     * 订单时间
     */
     @Expose
    private String orderTime;
    /**
     * 订单状态(1:订单未支付2:订单支付成功3:交易失败4:撤销成功)
     */
     @Expose
    private String orderStatus;
    /**
     * 订单金额
     */
     @Expose
    private Double orderMoney;
    /**
     * 订单付款码
     */
     @Expose
    private String orderBarcode;
    /**
     * 虚拟删除 0：正常 1：删除 2：审核
     */
     @Expose
    private String delFlag;

    // KEEP FIELDS - put your custom fields here
    public static final String WING_ORDER_NO = "0";//订单未支付
    public static final String WING_ORDER_SUCCESS = "1";//订单支付成功
    public static final String WING_ORDER_FAILURE = "2";//订单交易失败
    public static final String WING_ORDER_REFUND= "3";//订单退款成功
    public static final String WING_ORDER_CANCEL= "4";//订单已撤销
    // KEEP FIELDS END

    public PxWingPay() {
    }

    public PxWingPay(Long id) {
        this.id = id;
    }

    public PxWingPay(Long id, String objectId, String orderTable, String orderNo, String orderSerialNum, String orderTime, String orderStatus, Double orderMoney, String orderBarcode, String delFlag) {
        this.id = id;
        this.objectId = objectId;
        this.orderTable = orderTable;
        this.orderNo = orderNo;
        this.orderSerialNum = orderSerialNum;
        this.orderTime = orderTime;
        this.orderStatus = orderStatus;
        this.orderMoney = orderMoney;
        this.orderBarcode = orderBarcode;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getOrderTable() {
        return orderTable;
    }

    public void setOrderTable(String orderTable) {
        this.orderTable = orderTable;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getOrderSerialNum() {
        return orderSerialNum;
    }

    public void setOrderSerialNum(String orderSerialNum) {
        this.orderSerialNum = orderSerialNum;
    }

    public String getOrderTime() {
        return orderTime;
    }

    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Double getOrderMoney() {
        return orderMoney;
    }

    public void setOrderMoney(Double orderMoney) {
        this.orderMoney = orderMoney;
    }

    public String getOrderBarcode() {
        return orderBarcode;
    }

    public void setOrderBarcode(String orderBarcode) {
        this.orderBarcode = orderBarcode;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
