package com.psi.easymanager.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.Expose;
// KEEP INCLUDES END

/**
 * Smack UUID 记录
 */
public class SmackUUIDRecord implements java.io.Serializable {

    private Long id;
    /**
     * UUID
     */
     @Expose
    private String uuid;
    /**
     * 操作时间
     */
     @Expose
    private java.util.Date operateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SmackUUIDRecord() {
    }

    public SmackUUIDRecord(Long id) {
        this.id = id;
    }

    public SmackUUIDRecord(Long id, String uuid, java.util.Date operateTime) {
        this.id = id;
        this.uuid = uuid;
        this.operateTime = operateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public java.util.Date getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(java.util.Date operateTime) {
        this.operateTime = operateTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
