package com.psi.easymanager.module;

import com.psi.easymanager.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.psi.easymanager.dao.OfficeDao;
import com.psi.easymanager.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table "User".
 */
public class User implements java.io.Serializable {

    private Long id;
    /**
     * 
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 登录名
     */
     @Expose
    private String loginName;
    /**
     * 密码
     */
     @Expose
    private String password;
    /**
     * 工号
     */
     @Expose
    private String no;
    /**
     * 姓名
     */
     @Expose
    private String name;
    /**
     * 邮箱
     */
     @Expose
    private String email;
    /**
     * 电话
     */
     @Expose
    private String phone;
    /**
     * 手机
     */
     @Expose
    private String mobile;
    /**
     * 用户类型
     */
     @Expose
    private String userType;
    /**
     * 最后登陆IP
     */
     @Expose
    private String loginIp;
    /**
     * 最后登陆日期
     */
     @Expose
    private java.util.Date loginDate;
    /**
     * 是否允许登陆
     */
     @Expose
    private String loginFlag;
    /**
     * 头像
     */
     @Expose
    private String photo;
    /**
     * 原登录名
     */
     @Expose
    private String oldLoginName;
    /**
     * 新密码
     */
     @Expose
    private String newPassword;
    /**
     * 上次登陆IP
     */
     @Expose
    private String oldLoginIp;
    /**
     * 上次登陆日期
     */
     @Expose
    private java.util.Date oldLoginDate;
    /**
     * 虚拟删除 0：正常 1：删除 2：审核
     */
     @Expose
    private String delFlag;
    /**
     * 最大抹零限制
     */
     @Expose
    private Double maxTail;
    /**
     * 公司编码
     */
     @Expose
    private String companyCode;
    /**
     * 初始化密码
     */
     @Expose
    private String initPassword;
    /**
     * 初始登录名
     */
     @Expose
    private String imUserName;
    /**
     * 是否允许退菜(1:允许 0:不允许)
     */
     @Expose
    private String canRetreat;
    private long officeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient UserDao myDao;

    private Office company;
    private Long company__resolvedKey;


    // KEEP FIELDS - put your custom fields here
  //所在公司聊天密码
  private String mGroupId;
  //所在公司群组id
  private String mChatPwd;


  //能退菜
  public static final String CAN_RETREAT = "1";
  //不能退菜
  public static final String CAN_NOT_RETREAT = "0";
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String objectId, String loginName, String password, String no, String name, String email, String phone, String mobile, String userType, String loginIp, java.util.Date loginDate, String loginFlag, String photo, String oldLoginName, String newPassword, String oldLoginIp, java.util.Date oldLoginDate, String delFlag, Double maxTail, String companyCode, String initPassword, String imUserName, String canRetreat, long officeId) {
        this.id = id;
        this.objectId = objectId;
        this.loginName = loginName;
        this.password = password;
        this.no = no;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.mobile = mobile;
        this.userType = userType;
        this.loginIp = loginIp;
        this.loginDate = loginDate;
        this.loginFlag = loginFlag;
        this.photo = photo;
        this.oldLoginName = oldLoginName;
        this.newPassword = newPassword;
        this.oldLoginIp = oldLoginIp;
        this.oldLoginDate = oldLoginDate;
        this.delFlag = delFlag;
        this.maxTail = maxTail;
        this.companyCode = companyCode;
        this.initPassword = initPassword;
        this.imUserName = imUserName;
        this.canRetreat = canRetreat;
        this.officeId = officeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getUserDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getLoginIp() {
        return loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public java.util.Date getLoginDate() {
        return loginDate;
    }

    public void setLoginDate(java.util.Date loginDate) {
        this.loginDate = loginDate;
    }

    public String getLoginFlag() {
        return loginFlag;
    }

    public void setLoginFlag(String loginFlag) {
        this.loginFlag = loginFlag;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getOldLoginName() {
        return oldLoginName;
    }

    public void setOldLoginName(String oldLoginName) {
        this.oldLoginName = oldLoginName;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getOldLoginIp() {
        return oldLoginIp;
    }

    public void setOldLoginIp(String oldLoginIp) {
        this.oldLoginIp = oldLoginIp;
    }

    public java.util.Date getOldLoginDate() {
        return oldLoginDate;
    }

    public void setOldLoginDate(java.util.Date oldLoginDate) {
        this.oldLoginDate = oldLoginDate;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public Double getMaxTail() {
        return maxTail;
    }

    public void setMaxTail(Double maxTail) {
        this.maxTail = maxTail;
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getInitPassword() {
        return initPassword;
    }

    public void setInitPassword(String initPassword) {
        this.initPassword = initPassword;
    }

    public String getImUserName() {
        return imUserName;
    }

    public void setImUserName(String imUserName) {
        this.imUserName = imUserName;
    }

    public String getCanRetreat() {
        return canRetreat;
    }

    public void setCanRetreat(String canRetreat) {
        this.canRetreat = canRetreat;
    }

    public long getOfficeId() {
        return officeId;
    }

    public void setOfficeId(long officeId) {
        this.officeId = officeId;
    }

    /** To-one relationship, resolved on first access. */
    public Office getCompany() {
        long __key = this.officeId;
        if (company__resolvedKey == null || !company__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            OfficeDao targetDao = daoSession.getOfficeDao();
            Office companyNew = targetDao.load(__key);
            synchronized (this) {
                company = companyNew;
            	company__resolvedKey = __key;
            }
        }
        return company;
    }

    public void setCompany(Office company) {
        if (company == null) {
            throw new DaoException("To-one property 'officeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.company = company;
            officeId = company.getId();
            company__resolvedKey = officeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

  public String getGroupId() {
    return mGroupId;
  }

  public void setGroupId(String groupId) {
    mGroupId = groupId;
  }

  public String getChatPwd() {
    return mChatPwd;
  }

  public void setChatPwd(String chatPwd) {
    mChatPwd = chatPwd;
  }
    // KEEP METHODS END

}
