package com.psi.easymanager.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.psi.easymanager.module.PrintDetails;
import com.psi.easymanager.module.PrintDetailsCollect;
import com.psi.easymanager.module.PxOrderInfo;
import com.psi.easymanager.module.PxProductConfigPlan;

import com.psi.easymanager.module.PdConfigRel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PdConfigRel".
*/
public class PdConfigRelDao extends AbstractDao<PdConfigRel, Long> {

    public static final String TABLENAME = "PdConfigRel";

    /**
     * Properties of entity PdConfigRel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property OperateTime = new Property(2, java.util.Date.class, "operateTime", false, "OPERATE_TIME");
        public final static Property IsPrinted = new Property(3, Boolean.class, "isPrinted", false, "IS_PRINTED");
        public final static Property PxOrderInfoId = new Property(4, Long.class, "pxOrderInfoId", false, "PX_ORDER_INFO_ID");
        public final static Property DbPrintDetailsId = new Property(5, Long.class, "dbPrintDetailsId", false, "DB_PRINT_DETAILS_ID");
        public final static Property DbConfigId = new Property(6, Long.class, "dbConfigId", false, "DB_CONFIG_ID");
        public final static Property PdConfigRelId = new Property(7, Long.class, "PdConfigRelId", false, "PD_CONFIG_REL_ID");
    };

    private DaoSession daoSession;

    private Query<PdConfigRel> printDetailsCollect_DbPdConfigRelListQuery;

    public PdConfigRelDao(DaoConfig config) {
        super(config);
    }
    
    public PdConfigRelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PdConfigRel\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"TYPE\" TEXT," + // 1: type
                "\"OPERATE_TIME\" INTEGER," + // 2: operateTime
                "\"IS_PRINTED\" INTEGER," + // 3: isPrinted
                "\"PX_ORDER_INFO_ID\" INTEGER," + // 4: pxOrderInfoId
                "\"DB_PRINT_DETAILS_ID\" INTEGER," + // 5: dbPrintDetailsId
                "\"DB_CONFIG_ID\" INTEGER," + // 6: dbConfigId
                "\"PD_CONFIG_REL_ID\" INTEGER);"); // 7: PdConfigRelId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PdConfigRel\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PdConfigRel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        java.util.Date operateTime = entity.getOperateTime();
        if (operateTime != null) {
            stmt.bindLong(3, operateTime.getTime());
        }
 
        Boolean isPrinted = entity.getIsPrinted();
        if (isPrinted != null) {
            stmt.bindLong(4, isPrinted ? 1L: 0L);
        }
 
        Long pxOrderInfoId = entity.getPxOrderInfoId();
        if (pxOrderInfoId != null) {
            stmt.bindLong(5, pxOrderInfoId);
        }
 
        Long dbPrintDetailsId = entity.getDbPrintDetailsId();
        if (dbPrintDetailsId != null) {
            stmt.bindLong(6, dbPrintDetailsId);
        }
 
        Long dbConfigId = entity.getDbConfigId();
        if (dbConfigId != null) {
            stmt.bindLong(7, dbConfigId);
        }
 
        Long PdConfigRelId = entity.getPdConfigRelId();
        if (PdConfigRelId != null) {
            stmt.bindLong(8, PdConfigRelId);
        }
    }

    @Override
    protected void attachEntity(PdConfigRel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PdConfigRel readEntity(Cursor cursor, int offset) {
        PdConfigRel entity = new PdConfigRel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // operateTime
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isPrinted
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // pxOrderInfoId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // dbPrintDetailsId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // dbConfigId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // PdConfigRelId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PdConfigRel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOperateTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setIsPrinted(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setPxOrderInfoId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setDbPrintDetailsId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setDbConfigId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setPdConfigRelId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PdConfigRel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PdConfigRel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbPdConfigRelList" to-many relationship of PrintDetailsCollect. */
    public List<PdConfigRel> _queryPrintDetailsCollect_DbPdConfigRelList(Long PdConfigRelId) {
        synchronized (this) {
            if (printDetailsCollect_DbPdConfigRelListQuery == null) {
                QueryBuilder<PdConfigRel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PdConfigRelId.eq(null));
                printDetailsCollect_DbPdConfigRelListQuery = queryBuilder.build();
            }
        }
        Query<PdConfigRel> query = printDetailsCollect_DbPdConfigRelListQuery.forCurrentThread();
        query.setParameter(0, PdConfigRelId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPxOrderInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPrintDetailsDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getPxProductConfigPlanDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T3", daoSession.getPrintDetailsCollectDao().getAllColumns());
            builder.append(" FROM PdConfigRel T");
            builder.append(" LEFT JOIN OrderInfo T0 ON T.\"PX_ORDER_INFO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN PrintDetails T1 ON T.\"DB_PRINT_DETAILS_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN PxProductConfigPlan T2 ON T.\"DB_CONFIG_ID\"=T2.\"_id\"");
            builder.append(" LEFT JOIN PrintDetailsCollect T3 ON T.\"PD_CONFIG_REL_ID\"=T3.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PdConfigRel loadCurrentDeep(Cursor cursor, boolean lock) {
        PdConfigRel entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PxOrderInfo dbOrder = loadCurrentOther(daoSession.getPxOrderInfoDao(), cursor, offset);
        entity.setDbOrder(dbOrder);
        offset += daoSession.getPxOrderInfoDao().getAllColumns().length;

        PrintDetails dbPrintDetails = loadCurrentOther(daoSession.getPrintDetailsDao(), cursor, offset);
        entity.setDbPrintDetails(dbPrintDetails);
        offset += daoSession.getPrintDetailsDao().getAllColumns().length;

        PxProductConfigPlan dbConfig = loadCurrentOther(daoSession.getPxProductConfigPlanDao(), cursor, offset);
        entity.setDbConfig(dbConfig);
        offset += daoSession.getPxProductConfigPlanDao().getAllColumns().length;

        PrintDetailsCollect dbPdCollect = loadCurrentOther(daoSession.getPrintDetailsCollectDao(), cursor, offset);
        entity.setDbPdCollect(dbPdCollect);

        return entity;    
    }

    public PdConfigRel loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PdConfigRel> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PdConfigRel> list = new ArrayList<PdConfigRel>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PdConfigRel> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PdConfigRel> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
