package com.psi.easymanager.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.psi.easymanager.module.PxOrderInfo;
import com.psi.easymanager.module.PxProductConfigPlan;

import com.psi.easymanager.module.PrintDetailsCollect;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PrintDetailsCollect".
*/
public class PrintDetailsCollectDao extends AbstractDao<PrintDetailsCollect, Long> {

    public static final String TABLENAME = "PrintDetailsCollect";

    /**
     * Properties of entity PrintDetailsCollect.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OperateTime = new Property(1, java.util.Date.class, "operateTime", false, "OPERATE_TIME");
        public final static Property IsPrint = new Property(2, Boolean.class, "isPrint", false, "IS_PRINT");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property PxOrderInfoId = new Property(4, Long.class, "pxOrderInfoId", false, "PX_ORDER_INFO_ID");
        public final static Property DbConfigId = new Property(5, Long.class, "dbConfigId", false, "DB_CONFIG_ID");
    };

    private DaoSession daoSession;


    public PrintDetailsCollectDao(DaoConfig config) {
        super(config);
    }
    
    public PrintDetailsCollectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PrintDetailsCollect\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"OPERATE_TIME\" INTEGER," + // 1: operateTime
                "\"IS_PRINT\" INTEGER," + // 2: isPrint
                "\"TYPE\" TEXT," + // 3: type
                "\"PX_ORDER_INFO_ID\" INTEGER," + // 4: pxOrderInfoId
                "\"DB_CONFIG_ID\" INTEGER);"); // 5: dbConfigId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PrintDetailsCollect\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PrintDetailsCollect entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date operateTime = entity.getOperateTime();
        if (operateTime != null) {
            stmt.bindLong(2, operateTime.getTime());
        }
 
        Boolean isPrint = entity.getIsPrint();
        if (isPrint != null) {
            stmt.bindLong(3, isPrint ? 1L: 0L);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        Long pxOrderInfoId = entity.getPxOrderInfoId();
        if (pxOrderInfoId != null) {
            stmt.bindLong(5, pxOrderInfoId);
        }
 
        Long dbConfigId = entity.getDbConfigId();
        if (dbConfigId != null) {
            stmt.bindLong(6, dbConfigId);
        }
    }

    @Override
    protected void attachEntity(PrintDetailsCollect entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PrintDetailsCollect readEntity(Cursor cursor, int offset) {
        PrintDetailsCollect entity = new PrintDetailsCollect( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // operateTime
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // isPrint
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // pxOrderInfoId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // dbConfigId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PrintDetailsCollect entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOperateTime(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setIsPrint(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPxOrderInfoId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setDbConfigId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PrintDetailsCollect entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PrintDetailsCollect entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPxOrderInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPxProductConfigPlanDao().getAllColumns());
            builder.append(" FROM PrintDetailsCollect T");
            builder.append(" LEFT JOIN OrderInfo T0 ON T.\"PX_ORDER_INFO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN PxProductConfigPlan T1 ON T.\"DB_CONFIG_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PrintDetailsCollect loadCurrentDeep(Cursor cursor, boolean lock) {
        PrintDetailsCollect entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PxOrderInfo dbOrder = loadCurrentOther(daoSession.getPxOrderInfoDao(), cursor, offset);
        entity.setDbOrder(dbOrder);
        offset += daoSession.getPxOrderInfoDao().getAllColumns().length;

        PxProductConfigPlan dbConfig = loadCurrentOther(daoSession.getPxProductConfigPlanDao(), cursor, offset);
        entity.setDbConfig(dbConfig);

        return entity;    
    }

    public PrintDetailsCollect loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PrintDetailsCollect> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PrintDetailsCollect> list = new ArrayList<PrintDetailsCollect>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PrintDetailsCollect> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PrintDetailsCollect> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
