package com.psi.easymanager.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.psi.easymanager.module.PxComboGroup;
import com.psi.easymanager.module.PxFormatInfo;
import com.psi.easymanager.module.PxProductInfo;

import com.psi.easymanager.module.PxComboProductRel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ComboProductRel".
*/
public class PxComboProductRelDao extends AbstractDao<PxComboProductRel, Long> {

    public static final String TABLENAME = "ComboProductRel";

    /**
     * Properties of entity PxComboProductRel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property DelFlag = new Property(2, String.class, "delFlag", false, "DEL_FLAG");
        public final static Property Num = new Property(3, Integer.class, "num", false, "NUM");
        public final static Property Weight = new Property(4, Double.class, "weight", false, "WEIGHT");
        public final static Property PxComboGroupId = new Property(5, Long.class, "pxComboGroupId", false, "PX_COMBO_GROUP_ID");
        public final static Property PxProductId = new Property(6, Long.class, "pxProductId", false, "PX_PRODUCT_ID");
        public final static Property PxFormatId = new Property(7, Long.class, "pxFormatId", false, "PX_FORMAT_ID");
    };

    private DaoSession daoSession;


    public PxComboProductRelDao(DaoConfig config) {
        super(config);
    }
    
    public PxComboProductRelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ComboProductRel\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"DEL_FLAG\" TEXT," + // 2: delFlag
                "\"NUM\" INTEGER," + // 3: num
                "\"WEIGHT\" REAL," + // 4: weight
                "\"PX_COMBO_GROUP_ID\" INTEGER," + // 5: pxComboGroupId
                "\"PX_PRODUCT_ID\" INTEGER," + // 6: pxProductId
                "\"PX_FORMAT_ID\" INTEGER);"); // 7: pxFormatId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ComboProductRel\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PxComboProductRel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String delFlag = entity.getDelFlag();
        if (delFlag != null) {
            stmt.bindString(3, delFlag);
        }
 
        Integer num = entity.getNum();
        if (num != null) {
            stmt.bindLong(4, num);
        }
 
        Double weight = entity.getWeight();
        if (weight != null) {
            stmt.bindDouble(5, weight);
        }
 
        Long pxComboGroupId = entity.getPxComboGroupId();
        if (pxComboGroupId != null) {
            stmt.bindLong(6, pxComboGroupId);
        }
 
        Long pxProductId = entity.getPxProductId();
        if (pxProductId != null) {
            stmt.bindLong(7, pxProductId);
        }
 
        Long pxFormatId = entity.getPxFormatId();
        if (pxFormatId != null) {
            stmt.bindLong(8, pxFormatId);
        }
    }

    @Override
    protected void attachEntity(PxComboProductRel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PxComboProductRel readEntity(Cursor cursor, int offset) {
        PxComboProductRel entity = new PxComboProductRel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // delFlag
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // num
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // weight
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // pxComboGroupId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // pxProductId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // pxFormatId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PxComboProductRel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDelFlag(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNum(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setWeight(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setPxComboGroupId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setPxProductId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setPxFormatId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PxComboProductRel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PxComboProductRel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPxComboGroupDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPxProductInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getPxFormatInfoDao().getAllColumns());
            builder.append(" FROM ComboProductRel T");
            builder.append(" LEFT JOIN ComboGroup T0 ON T.\"PX_COMBO_GROUP_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ProductInfo T1 ON T.\"PX_PRODUCT_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN FormatInfo T2 ON T.\"PX_FORMAT_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PxComboProductRel loadCurrentDeep(Cursor cursor, boolean lock) {
        PxComboProductRel entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PxComboGroup dbComboGroup = loadCurrentOther(daoSession.getPxComboGroupDao(), cursor, offset);
        entity.setDbComboGroup(dbComboGroup);
        offset += daoSession.getPxComboGroupDao().getAllColumns().length;

        PxProductInfo dbProduct = loadCurrentOther(daoSession.getPxProductInfoDao(), cursor, offset);
        entity.setDbProduct(dbProduct);
        offset += daoSession.getPxProductInfoDao().getAllColumns().length;

        PxFormatInfo dbFormat = loadCurrentOther(daoSession.getPxFormatInfoDao(), cursor, offset);
        entity.setDbFormat(dbFormat);

        return entity;    
    }

    public PxComboProductRel loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PxComboProductRel> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PxComboProductRel> list = new ArrayList<PxComboProductRel>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PxComboProductRel> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PxComboProductRel> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
