package com.psi.easymanager.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.psi.easymanager.module.PxWeiXinpay;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PxWeiXinpay".
*/
public class PxWeiXinpayDao extends AbstractDao<PxWeiXinpay, Long> {

    public static final String TABLENAME = "PxWeiXinpay";

    /**
     * Properties of entity PxWeiXinpay.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Key = new Property(2, String.class, "key", false, "KEY");
        public final static Property AppId = new Property(3, String.class, "appId", false, "APP_ID");
        public final static Property MacId = new Property(4, String.class, "macId", false, "MAC_ID");
        public final static Property DelFlag = new Property(5, String.class, "delFlag", false, "DEL_FLAG");
    };


    public PxWeiXinpayDao(DaoConfig config) {
        super(config);
    }
    
    public PxWeiXinpayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PxWeiXinpay\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"KEY\" TEXT," + // 2: key
                "\"APP_ID\" TEXT," + // 3: appId
                "\"MAC_ID\" TEXT," + // 4: macId
                "\"DEL_FLAG\" TEXT);"); // 5: delFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PxWeiXinpay\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PxWeiXinpay entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(3, key);
        }
 
        String appId = entity.getAppId();
        if (appId != null) {
            stmt.bindString(4, appId);
        }
 
        String macId = entity.getMacId();
        if (macId != null) {
            stmt.bindString(5, macId);
        }
 
        String delFlag = entity.getDelFlag();
        if (delFlag != null) {
            stmt.bindString(6, delFlag);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PxWeiXinpay readEntity(Cursor cursor, int offset) {
        PxWeiXinpay entity = new PxWeiXinpay( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // key
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // appId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // macId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // delFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PxWeiXinpay entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKey(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAppId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMacId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDelFlag(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PxWeiXinpay entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PxWeiXinpay entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
